START transaction;

DROP DATABASE IF EXISTS `accidinfo` ;
CREATE DATABASE `accidinfo` ;
USE `accidinfo` ;
CREATE TABLE `PERSONNE`(
N°PERS SERIAL UNIQUE,
NOM TEXT NOT NULL,
PRENOM TEXT NOT NULL,
ADRESSE TEXT NOT NULL,
AGE INT CHECK (AGE > 18),
PRIMARY KEY (N°PERS)

);
CREATE TABLE `VEHICULE`(
N°VEH INT,
MARQUE TEXT NOT NULL,
VEH_TYPE TEXT,
PRIMARY KEY (N°VEH)
);
CREATE TABLE `CONDUCTEUR`(
N°PERS INT,
N°VEH INT,
NBACC INT,
PRIMARY KEY (N°PERS, N°VEH)
);
CREATE TABLE `ACCIDENT`(
N°ACC INT,
ACC_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
DEPT TEXT NOT NULL CHECK (DEPT > "0" and DEPT < "81"),
PRIMARY KEY (N°ACC)
);
CREATE TABLE `VEHPART`(
N°ACC INT,
N°VEH INT,
N°COND INT,
PRIMARY KEY (N°ACC,N°VEH)
);
CREATE TABLE `BLESSE`(
N°ACC INT,
N°PERS INT,
N°VEH INT,
GRAVITE VARCHAR(20),
PRIMARY KEY (N°ACC, N°PERS)
);

CREATE TABLE GRAVITES(
GRAVITE VARCHAR(20) primary key
);
INSERT INTO GRAVITES VALUES
('Bénigne'), ('Légère'), (' Sérieuse'), ('Grave'), ('Fatale');

commit ;